module.exports = {
    ROPSTEN_NODE_URL: process.env.ROPSTEN_NODE_URL,
    INFURA_ROPSTEN_URL: process.env.INFURA_ROPSTEN_URL,
    TOKEN_TOTAL_SUPPLY: 135000000,
    TOKEN_CONTRACT_OWNER: process.env.TOKEN_CONTRACT_OWNER
};