module.exports = {
    ROPSTEN_NODE_URL: process.env.ROPSTEN_NODE_URL,
    INFURA_ROPSTEN_URL: process.env.INFURA_ROPSTEN_URL,
    INFURA_MAINNET_URL: process.env.INFURA_MAINNET_URL,
    TOKEN_TOTAL_SUPPLY: 135000000,
    TOKEN_CONTRACT_OWNER: process.env.TOKEN_CONTRACT_OWNER,
    HD_WALLET_MNEMONIC: process.env.HD_WALLET_MNEMONIC
};